data(mtcars)
summary(mtcars)
plot(mtcars)
boxplot(mtcars)
names(mtcars)
plot(mtcars$wt, mtcars$mpg)
plot(mtcars$mpg, mtcars$wt)
plot(mtcars$mpg, mtcars$wt)
head(mtcars)
plot(mtcars$hp, xlab = "X variable", mtcars$wt, ylab = "Y variable")